services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  service_a:
    build: ./service_a
    env_file: ./service_a/.env
    depends_on: [rabbitmq]
    ports:
      - "8000:8000"

  service_b:
    build: ./service_b
    env_file: ./service_b/.env
    depends_on: [rabbitmq, mongodb, service_a]
    restart: on-failure
    ports:
      - "8001:8001"

  worker:
    build: ./worker
    env_file: ./worker/.env
    depends_on: [rabbitmq, mongodb, service_a]
    restart: on-failure

volumes:
  mongo_data:
